export const recipes = [
  {
    id: 1,
    recipeName: "Spicy Chicken Stir-Fry",
    ingredients: [
      "Chicken breasts",
      "Soy sauce",
      "Sriracha sauce",
      "Garlic",
      "Vegetable oil",
      "Bell pepper",
      "Onion",
      "Broccoli florets",
      "Salt",
      "Pepper",
    ],
    cookingInstructions: [
      "Mix soy sauce, sriracha sauce, and minced garlic in a bowl.",
      "Slice chicken breasts into strips and pour sauce mixture over them.",
      "Heat oil in a pan and stir-fry chicken until cooked.",
      "Add bell pepper, onion, and broccoli. Cook until vegetables are tender-crisp.",
      "Season with salt and pepper to taste.",
      "Serve hot.",
    ],
    cuisineType: "Asian",
    imageURL:
      "https://img.freepik.com/free-photo/chicken-stir-fry-vegetables_123827-21544.jpg?w=1060&t=st=1688243035~exp=1688243635~hmac=581df2a8b9b88a07c9a42c8af0eaec4fe93eb04ac5973e400c2a52a7f6e474e3",
  },
  {
    id: 2,
    recipeName: "Classic Margherita Pizza",
    ingredients: [
      "Pizza dough",
      "Tomato sauce",
      "Mozzarella cheese",
      "Fresh basil leaves",
      "Olive oil",
      "Salt",
      "Pepper",
    ],
    cookingInstructions: [
      "Preheat oven to the recommended temperature for the pizza dough.",
      "Roll out the pizza dough into a round shape.",
      "Spread tomato sauce evenly over the dough.",
      "Top with mozzarella cheese and fresh basil leaves.",
      "Drizzle with olive oil and season with salt and pepper.",
      "Bake in the oven until the crust is golden and the cheese is melted and bubbly.",
      "Remove from the oven, let it cool slightly, and serve.",
    ],
    cuisineType: "Italian",
    imageURL:
      "https://img.freepik.com/free-photo/salmon-caesar-pizza-table_140725-6798.jpg?w=740&t=st=1688243087~exp=1688243687~hmac=488abbbb86b1168c43005977eed0244fd9579d7f6a3212c7d3aa0bbda2aafb36",
  },
  {
    id: 3,
    recipeName: "Creamy Garlic Parmesan Pasta",
    ingredients: [
      "Pasta",
      "Garlic",
      "Butter",
      "Heavy cream",
      "Parmesan cheese",
      "Salt",
      "Black pepper",
      "Fresh parsley",
    ],
    cookingInstructions: [
      "Cook pasta according to package instructions.",
      "In a pan, melt butter over medium heat and sauté minced garlic until fragrant.",
      "Add heavy cream and bring to a simmer.",
      "Stir in grated Parmesan cheese until melted and smooth.",
      "Season with salt and black pepper.",
      "Toss the cooked pasta in the creamy sauce until well coated.",
      "Garnish with fresh parsley and serve hot.",
    ],
    cuisineType: "Italian",
    imageURL:
      "https://img.freepik.com/free-photo/salmon-fettuccini-with-cream-sauce-parmesan-avocado_140725-5910.jpg?w=740&t=st=1688243135~exp=1688243735~hmac=b93a002eb5efb7792459abdee0ab202bdaa8eb3682fbb93ee9f87504ef0ed1f4",
  },
  {
    id: 4,
    recipeName: "Beef Tacos",
    ingredients: [
      "Ground beef",
      "Taco seasoning",
      "Flour tortillas",
      "Lettuce",
      "Tomato",
      "Onion",
      "Cheddar cheese",
      "Sour cream",
      "Salsa",
    ],
    cookingInstructions: [
      "In a skillet, cook ground beef until browned. Drain excess fat.",
      "Add taco seasoning and water as per package instructions. Simmer until heated through.",
      "Warm flour tortillas in a separate pan or in the oven.",
      "Assemble the tacos by filling each tortilla with the cooked ground beef.",
      "Top with shredded lettuce, diced tomato and onion, grated cheddar cheese, sour cream, and salsa.",
      "Fold the tortillas and serve immediately.",
    ],
    cuisineType: "Mexican",
    imageURL:
      "https://img.freepik.com/free-photo/mexican-tacos-with-beef-tomato-sauce-salsa_2829-14227.jpg?w=1060&t=st=1688243967~exp=1688244567~hmac=0d6456ec8ffff161616d90b57b305531ed38027938036c71ea34d1332f32438c",
  },
  {
    id: 5,
    recipeName: "Chicken Alfredo Pasta",
    ingredients: [
      "Chicken breast",
      "Fettuccine pasta",
      "Garlic",
      "Butter",
      "Heavy cream",
      "Parmesan cheese",
      "Salt",
      "Black pepper",
      "Fresh parsley",
    ],
    cookingInstructions: [
      "Cook fettuccine pasta according to package instructions.",
      "Season chicken breast with salt and pepper. Cook in a separate pan until no longer pink. Set aside.",
      "In the same pan, melt butter over medium heat and sauté minced garlic until fragrant.",
      "Add heavy cream and bring to a simmer.",
      "Stir in grated Parmesan cheese until melted and smooth.",
      "Slice the cooked chicken breast into strips and add it to the sauce.",
      "Drain the cooked pasta and toss it in the creamy sauce.",
      "Garnish with fresh parsley and serve hot.",
    ],
    cuisineType: "Italian",
    imageURL:
      "https://img.freepik.com/free-photo/pasta-meal-pan-with-raw-pasta-mushroom-parsley-tomato_176474-6903.jpg?w=1060&t=st=1688244000~exp=1688244600~hmac=6e04ba171ccb316b3cb16f81656993677dfaca16be254b0193fcdaac0762e669",
  },
];
